# yaml-language-server: $schema=settings.schema.yaml
$schema: "./settings.schema.yaml"
api:
  database_uri: mongodb://mongoadmin:secret@127.0.0.1:27017/db?authSource=admin # "mongodb://mongoadmin:secret@db:27017/db?authSource=admin" for Docker Compose
  accounts:
    # get from https://api.innohassle.ru/accounts/v0/tokens/generate-service-token?sub=service-name&scopes=users&only_for_me=true
    api_jwt_token: null
  printers_list: []
  scanners_list: []
bot:
  database_uri: mongodb://mongoadmin:secret@127.0.0.1:27017/db?authSource=admin # "mongodb://mongoadmin:secret@db:27017/db?authSource=admin" for Docker Compose
  api_url: http://127.0.0.1:8000
  bot_token: null
  proxy_url: null # protocol://user:password@host:port
